name: gh-pages-push-automation
on:
  push:
    branches: [ "main" ]
jobs:
  gh-pages-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-gh-pages@v3
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
