name: gh-pages-push-automation
on:
  push:
    branches: [ "main" ]
jobs:
  gh-pages-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run : npm install --legacy-peer-deps
      - run : gatsby build --prefix-paths
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
